databases:
  - name: somenewsapp-db
    databaseName: somenewsapp_db
    user: somenewsapp_db_user

services:
  - type: web
    name: somenewsapp
    env: python3
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: somenewsapp
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
